<a href="https://colab.research.google.com/github/Rom4rgc/Tareas-Mate/blob/main/Guiamate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# matrices
A = np.array([[3, 7, 9], [5, 8, 10]])
B = np.array([[1, 4, 7], [2, 5, 9]])
C = np.array([[1, 7], [2, 8], [4, 9]])
D = np.array([[1 + 1j, -1 + 1j], [1 + 1j, 1 - 1j]])
E = np.array([[1, 3], [4, 7]])
F = np.array([[0, 0, 0], [0, 1 - 1j, -1 - 1j], [0, -1 + 1j, 2]])
G = np.array([[np.sqrt(1/2), np.sqrt(1/3), -np.sqrt(1/6)],
              [-np.sqrt(1/2), np.sqrt(1/3), -np.sqrt(1/6)],
              [0, np.sqrt(2/6), np.sqrt(1/3)]])

# Operación 1: Suma A + B
A_plus_B = A + B
print("A + B =\n", A_plus_B)

# Operación 2: Suma E + D
D_calculated = np.array([[ (1 + 1j)/2, (-1 + 1j)/2],
                         [ (1 + 1j)/2, (1 - 1j)/2]])
E_plus_D = E + D_calculated
print("E + D =\n", E_plus_D)

# Operación 3: Multiplicación AC
AC = np.dot(A, C)
print("AC =\n", AC)

# Operación 4: Multiplicación CE
CE = np.dot(C, E)
print("CE =\n", CE)

# Operación 5: Multiplicación CB
CB = np.dot(C, B)
print("CB =\n", CB)


A + B =
 [[ 4 11 16]
 [ 7 13 19]]
E + D =
 [[1.5+0.5j 2.5+0.5j]
 [4.5+0.5j 7.5-0.5j]]
AC =
 [[ 53 158]
 [ 61 189]]
CE =
 [[29 52]
 [34 62]
 [40 75]]
CB =
 [[ 15  39  70]
 [ 18  48  86]
 [ 22  61 109]]
